# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('teksan.ico', '.'),
        ('../fonts/Vazir.ttf', 'fonts'),
        ('../icons/*', 'icons'),
        ('convercation.py', '.'),
        ('option_files.py', '.'),
        ('sidebar.py', '.'),
        ('user_input.py', '.'),
        ('.env', '.'),
    ],
    hiddenimports=[
        'PIL._tkinter_finder',
        'customtkinter',
        'google.generativeai',
        'wmi',
        'dotenv',
        'tkinter',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TekSan',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        'vcruntime140.dll',
        'vcruntime140_1.dll',
        'msvcp140.dll',
        'python3*.dll',
        '_ssl.pyd',
        '_socket.pyd',
        'unicodedata.pyd',
        '_ctypes.pyd',
        '_queue.pyd',
        '_multiprocessing.pyd',
        'pyexpat.pyd',
        '_asyncio.pyd',
        '_overlapped.pyd',
        'select.pyd',
        '_wmi.pyd',
        'win32api.pyd',
        'win32event.pyd',
        'win32trace.pyd',
        'win32ui.pyd',
        '_win32sysloader.pyd',
        'PIL/*.pyd',
        'grpc/_cython/*.pyd',
        'charset_normalizer/*.pyd',
        'google/_upb/*.pyd',
        'libcrypto*.dll',
        'libssl*.dll',
        'libffi*.dll',
        'tcl86t.dll',
        'tk86t.dll',
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='teksan.ico',
    uac_admin=True
)
